name: Test, Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test
    
  get-version:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get current version
        id: version
        run: |
          current_version=$(jq -r '.version' package.json)
          echo "Current version is: $current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, get-version]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alejofl/ci-api:${{ needs.get-version.outputs.version }}